notifier:
  sources:
    export-api:
      ge-solutions:
        access-key: abcdefghijklmnopqrstuvwxyz
        server-url: https://ge.solutions-team.gradle.com
  destinations:
    slack-webhook:
      testing-server:
        webhook-url: https://hooks.slack.com/services/ABCDEFG/HIJKLMNOP/QRSTUVWXYZ
