spring:
  main:
    banner-mode: off

notification:
  rules:
    ci-build-failed:
      message: "The `%{projectName}` build has failed in CI.\n\nBuild Scan: %{link}"
      destinations:
        - my-company-slack
      condition:
        outcome: failed
        tags: [ CI ]
