notifier:
  export-api:
    sources:
      ge-solutions:
        access-key: abcdefghijklmnopqrstuvwxyz
        server-url: https://ge.solutions-team.gradle.com
  slack:
    destinations:
      testing-server:
        webhook-url: https://hooks.slack.com/services/ABCDEFG/HIJKLMNOP/QRSTUVWXYZ
