name: Build

on: [ push, workflow_dispatch ]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Check out project
        uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
      - uses: gradle/wrapper-validation-action@v3
      - name: Set up Gradle
        uses: gradle/gradle-build-action@v3
      - name: Build
        run: ./gradlew clean build
        env:
          ORG_GRADLE_PROJECT_agreeToGradleTermsOfService: true
